/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_smartproxy_crypto_CryptoUtils */

#ifndef _Included_me_smartproxy_crypto_CryptoUtils
#define _Included_me_smartproxy_crypto_CryptoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_smartproxy_crypto_CryptoUtils
 * Method:    exec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_smartproxy_crypto_CryptoUtils_exec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     me_smartproxy_crypto_CryptoUtils
 * Method:    getABI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_smartproxy_crypto_CryptoUtils_getABI
  (JNIEnv *, jclass);

/*
 * Class:     me_smartproxy_crypto_CryptoUtils
 * Method:    testEncrypt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_smartproxy_crypto_CryptoUtils_testEncrypt
  (JNIEnv *, jclass);

/*
 * Class:     me_smartproxy_crypto_CryptoUtils
 * Method:    initEncryptor
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_smartproxy_crypto_CryptoUtils_initEncryptor
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     me_smartproxy_crypto_CryptoUtils
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_smartproxy_crypto_CryptoUtils_encrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     me_smartproxy_crypto_CryptoUtils
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_smartproxy_crypto_CryptoUtils_decrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
